### PR TITLE
[Reviewer: Andy] Fix scribbler in additional home domains

### LINKED ISSUE #1228: scribbler in stack.cpp init_stack()
[This code](https://github.com/Metaswitch/sprout/commit/99e4433afe75a4d70ae11445d58183fc253dabf8/sprout/stack.cpp#L633-634) calls `pj_strdup2` on an uninitialized pointer.  

That won't work - it'll just scribble into whatever the pointer happens to be pointing at.

### PR DESCRIPTION
**Pull request by mirw**
Fixes #1228.

Tested live.

Matt

### CODE REVIEW

File: sprout/stack.cpp [hunk 1]
```diff
@@ -630,8 +630,9 @@ pj_status_t init_stack(const std::string& system_name,
     {
       stack_data.home_domains.insert(*ii);
 
-      pj_str_t* domain;
-      pj_strdup2(stack_data.pool, domain, ii->c_str());
+      // We can't allocate using PJSIP memory allocation here because it's not yet initialized.
+      pj_str_t* domain = (pj_str_t*)malloc(sizeof(pj_str_t));
+      *domain = pj_str(strdup(ii->c_str()));
```
Comment (bossmc) [inline sprout/stack.cpp]: This leaks memory, but so does line 595 (and 591 [and probably others]) otherwise fine.

**Comment by bossmc** [comment]
Ugly but acceptable.
