### PR TITLE
[Reviewer: Graeme] Map HSS responses to SIP failure codes correctly

### LINKED ISSUE #1453: Sprout returns 504 SERVER_TIMEOUT error when service profile doesn't contain a public identity
[This branch of code](https://github.com/Metaswitch/sprout/blob/092299363e18bb0be15b18c25ecacba1001ea64d/src/registrar.cpp#L630) is very confused. We enter it if update_registration_state doesn't return `HTTP_OK`. This can happen either because we've failed to contact Homestead/the HSS or because we've received some invalid IFCs (and possibly other reasons). However, we set the terribly named `st_code` variable to `PJSIP_SC_SERVER_TIMEOUT` regardless, and then we drop a completely contradictory log - `"rejecting register request with invalid public/private identity"`.

The impact of this is that a REGISTER request can fail due to a `504 SERVER TIMEOUT` when in fact no servers have timed out, we've just got some bad state in Homestead/the HSS. This is pretty confusing. Similarly, I assume that if a request to Homestead/the HSS genuinely times out then we'll still drop the log above, which would also be confusing.

Seen whilst running the live tests on an AIO node with Sprout at current dev, i.e. `092299363e18bb0be15b18c25ecacba1001ea64d`.

### PR DESCRIPTION
**Pull request by richardwhiuk**
Treat a server failure (either caused by a failure by the HSS or by a failure
to decode the response) as a SIP 500 Internal Server Error.

Log an appropriate message instead of assuming all failures are caused by
incorrect registration details, including the return code and HSS response
where appropriate.

This fixes #1453 

I've checked that all the UTs pass, and that the two new UTs fail without this code.

### CODE REVIEW

File: include/hss_sip_mapping.h [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+#ifndef HSS_SIP_MAPPING_H__
+#define HSS_SIP_MAPPING_H__
+
+extern "C" {
+#include <pjsip.h>
+}
+
+#include "acr.h"
+
+bool process_hss_sip_failure(HTTPCode http_code,
```
Comment (graemerobertson) [inline include/hss_sip_mapping.h]: Can you write a comment for this function, either here or in the CPP file? In particular, calling PJUtils::respond_stateless is a fairly major action so it would be good if this was clear from looking at the function definition.

(We're generally fairly inconsistent about a) writing function comments and b) where we write function comments, particularly in Sprout, which isn't great)

File: src/hss_sip_mapping.cpp [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+  int st_code = PJSIP_SC_OK;
+
+  if ((http_code != HTTP_OK) || (regstate != HSSConnection::STATE_REGISTERED))
+  {
+    // We failed to register this subscriber at the HSS. This may be because
+    // the HSS is unavilable, the public identity doesn't exist, the public
+    // identity doesn't belong to the private identity, or there was an error
+    // communicating with the HSS.
+
+    if (http_code == HTTP_OK)
```
Comment (graemerobertson) [inline src/hss_sip_mapping.cpp]: Should this be a switch statement?

File: src/hss_sip_mapping.cpp [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+{
+  int st_code = PJSIP_SC_OK;
+
+  if ((http_code != HTTP_OK) || (regstate != HSSConnection::STATE_REGISTERED))
+  {
+    // We failed to register this subscriber at the HSS. This may be because
+    // the HSS is unavilable, the public identity doesn't exist, the public
+    // identity doesn't belong to the private identity, or there was an error
+    // communicating with the HSS.
+
```
Comment (graemerobertson) [inline src/hss_sip_mapping.cpp]: I don't think we'd normally put a blank line here. Also both new files have blank lines at the end of them which is my absolute least favourite thing, the one thing I stand against in fact.

Obviously this isn't exactly 'must address' feedback.

File: src/hss_sip_mapping.cpp [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+    if (http_code == HTTP_OK)
+    {
+      TRC_ERROR("Rejecting %s request following failure to register on the HSS: %s",
+                type, regstate.c_str());
```
Comment (graemerobertson) [inline src/hss_sip_mapping.cpp]: Can we rename `type` to `sip_msg_type` or something that makes it clear what it is? I'd probably actually call it `sip_msg_type_log_str` but that's fairly long-winded.

File: src/hss_sip_mapping.cpp [hunk 5]
```diff
@@ -0,0 +1,112 @@
...
+      // response
+      TRC_ERROR("Rejecting %s request following error communicating with the HSS",
+                type);
+
+      st_code = PJSIP_SC_INTERNAL_SERVER_ERROR;
+    }
+    else
+    {
+      TRC_ERROR("Rejecting %s request following response %d from HSS",
+                type, http_code);
```
Comment (graemerobertson) [inline src/hss_sip_mapping.cpp]: Shouldn't we set `st_code` to something other than PJSIP_SC_OK here?

**Comment by graemerobertson** [comment]
I've reviewed, looks basically all fine.

Two further bits of feedback...
* This presumably breaks Sprout coverage, and you presumably already know that because I saw you asking about how to run the UT coverage. I don't much care whether you fix this by adding some more boring/identical UTs or just LCOV_EXCL offending branches (assuming they're essentially no-ops).
* Your github username is absurd.

File: include/hss_sip_mapping.h (hunk 1 above)
Comment (richardwhiuk) [inline include/hss_sip_mapping.h]: Yes, done.

File: src/hss_sip_mapping.cpp (hunk 2 above)
Comment (richardwhiuk) [inline src/hss_sip_mapping.cpp]: Done.

File: src/hss_sip_mapping.cpp (hunk 3 above)
Comment (richardwhiuk) [inline src/hss_sip_mapping.cpp]: Fixed

File: src/hss_sip_mapping.cpp (hunk 4 above)
Comment (richardwhiuk) [inline src/hss_sip_mapping.cpp]: I've renamed it, and clarified it's usage in the function comment.

File: src/hss_sip_mapping.cpp (hunk 5 above)
Comment (richardwhiuk) [inline src/hss_sip_mapping.cpp]: Yes, I was dithering what the correct answer was. I've defaulted to just returning the same as before on the assumption it represents some unknown error that will disappear if the subscriber retries later.
