### PR TITLE
[reviewer: Rob] Fixed auth case where algorithm not specified in header

### LINKED ISSUE #1176: Sprout crashes with segment trap on any ipsec registration
On the K load sprout will crash for any ipsec registration attempt.  I have the gather_diags output on both sprouts along with the SAS traces.

### PR DESCRIPTION
**Pull request by alango**
Fixes #1176

### CODE REVIEW

File: sprout/authentication.cpp [hunk 1]
```diff
@@ -667,6 +667,8 @@ pj_bool_t authenticate_rx_request(pjsip_rx_data* rdata)
   pj_status_t status;
   bool is_register = (rdata->msg_info.msg->line.req.method.id == PJSIP_REGISTER_METHOD);
   SNMP::SuccessFailCountTable* auth_stats_table = NULL;
+  rapidjson::StringBuffer buffer;
+  rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
```
Comment (rkd-msw) [inline sprout/authentication.cpp]: This doesn't seem to be used - is this right? (And does it not trigger an 'unused variable' compiler warning?).

File: sprout/authentication.cpp [hunk 2]
```diff
@@ -706,13 +713,23 @@ pj_bool_t authenticate_rx_request(pjsip_rx_data* rdata)
...
-    auth_stats_table->increment_attempts();
-
-    std::string impi = PJUtils::pj_str_to_string(&credentials->username);
-    std::string nonce = PJUtils::pj_str_to_string(&credentials->nonce);
-    uint64_t cas = 0;
-
-    av = av_store->get_av(impi, nonce, cas, trail);
+    if (auth_stats_table == NULL)
+    {
+      // Authorisation header did not specify an algorithm, so check the av for
```
Comment (rkd-msw) [inline sprout/authentication.cpp]: Authori**z**ation , I think.

**Comment by rkd-msw** [comment]
Looks good.
