### PR TITLE
[Reviewer: RKD] Send a 500 when we fail to store a nonce

### LINKED ISSUE #1404: Sprout will challenge registrations repeatedly if memcached is down, rather than returning a 5xx error
#### Symptoms

A mailing list user provided logs relating to registration failure, and I spotted this:

```
15-04-2016 11:00:01.578 UTC Debug memcachedstore.cpp:410: Read for impi\\2010000006@xflowresearch.com on replica 0 returned SUCCESS
15-04-2016 11:00:01.578 UTC Debug memcachedstore.cpp:453: Read 23976 bytes from table impi key 2010000006@xflowresearch.com, CAS = 2102
15-04-2016 11:00:01.578 UTC Debug impistore.cpp:754: Retrieved IMPI for 2010000006@xflowresearch.com
{"authChallenges":[{"type":"digest","nonce":"4358cc39032b496c","nc":2,"expires":1460718011,"correlator":"z9hG4bKPjQTc8JtYPma.arD9xUebTmV4zA5PCqjky","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"4b68593b6d072be4","nc":2,"expires":1460718011,"correlator":"z9hG4bKPjVU8wIsY2IRKfc.VeOD1BG5VOBGneCIsT","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"39a711d42cea85d3","nc":2,"expires":1460718011,"correlator":"z9hG4bKPjnfLjnk1tnVrnO.ZpVAZU15WZxbzjqUDY","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"7f0a06595eb5e44c","nc":2,"expires":1460718014,"correlator":"z9hG4bKPjWS7M68EZ2Xu1SrlqVjpQ4CumH2oxFT61","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"4ca3d7902b7e926f","nc":2,"expires":1460718014,"correlator":"z9hG4bKPj.IhZIt-3cBpA2Gd4khsy3bHRuVG5MFlm","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"227c81e45b1a4684","nc":2,"expires":1460718014,"correlator":"z9hG4bKPjWq2Z4J0oW55ip138nNOGcFOzutIv-6ju","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"30d1c85b76da5308","nc":2,"expires":1460718014,"correlator":"z9hG4bKPjFuCiS6Zx8zy42tmLR9G1bzrMPKNekqvH","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"6ea273bb57f243ef","nc":2,"expires":1460718014,"correlator":"z9hG4bKPjz5oTnmOsHe636.Dr5LJ0FS3VuJ-C9yqL","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"38e8578d7173fae0","nc":2,"expires":1460718014,"correlator":"z9hG4bKPjUbq1ImXj8v8rYxDpTXvJiyBls0ezpnSW","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"49913bd6176df9ab","nc":2,"expires":1460718014,"correlator":"z9hG4bKPjsu80AwNi8idk-IlN4MCDMYTRAFKZmWEq","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"34bf3dbd53822bec","nc":2,"expires":1460718015,"correlator":"z9hG4bKPjfc4RNcKSYDfExxH0aUvNeN3.cFyBanuR","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"34fe5a0155292e12","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjvapDia.jTq8-8HApLliQyuH6cq2aE.9A","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"1f1b6df238db97f3","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjC4txptGEoYP5v39FT4HJ9mL-UI8ZyX0M","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"05d0d2e96e9875b7","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjXY5hFGRAxioPS3Ip5wlE5RN2JH-Q73Xx","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"62ca94db04da363b","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjzu1XY4PzfhxMgsMTXtgYKLSq0kN76cXc","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"29daac01688eae4c","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjNYd5as4b8U2jbAyBXQ4qbFPBbV1j50Yl","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"5f281e3c0da5230e","nc":2,"expires":1460718016,"correlator":"z9hG4bKPj4p.baCOclOjzMJcdcpc8N-1j9.8FwIEL","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"373d75f937fc5613","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjiuNuFNaEh.wbXRoPaVqDddEplD8KiN2d","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"308ebdfc43570ba9","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjLXEhSuPnkHzZ490RVQi9V2yLEsumYFEe","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"34823dc775d6dbd1","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjPds6-NMvvh8WRnl4.KW6U5iqzPE9IUs5","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"5d1f7ade5dfec228","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjdGCgDK7Pz2My2.hL-LtB6VUuzGqM-mFk","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"2f6834a57a98a806","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjAoS.P1EDLpBu11IP..1sXGcUJcOmZYHo","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"66520a07144ff26c","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjQU3GO.0WZf5qgCQvuf6sfWwok-SogJEB","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"422cdd3d0a626aa2","nc":1,"expires":1460718016,"correlator":"z9hG4bKPj68DKHviso15GX7vR24xS.DvuPWQ1r.NH","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"2cf16f1e5fe771fe","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjQ7Q.D-V-El7xqxIAZTXFyl8SpblVE1Na","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"29d057fa78023c94","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjyYRXccnMpIFzM1HQfGV31Ctqa2K2BkPt","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"4aa226972ab95f6e","nc":2,"expires":1460718016,"correlator":"z9hG4bKPj-BF2vmzuD4meq2nLtOEc34W3rf7b.G0E","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"798ae762300c5222","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjU5yuWAQTaX5dWHMB0K.o0Ci3ORT2TQ40","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"64098e7a076ba358","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjzAbE9-E4DN68FnsfOnNKLTAetHTbT.Hq","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"6f590a33580083b4","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjL0FJw2vw.HxK3RtEK1PQvuauTto764jp","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"225b6c1f75ad19f3","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjGYtZ1fJrOnCc2VRfITwgaiv1HxWiTpqK","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"12301bbd2eeb494d","nc":2,"expires":1460718016,"correlator":"z9hG4bKPjq0M2OWDuAUdNeHfAycqKA-1kgjeAKu82","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"551265374112df8e","nc":1,"expires":1460718017,"correlator":"z9hG4bKPjA3j28N3HN-QrRhSPtQtQWGdNJ354OlDI","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"57db2f4458f23e1e","nc":2,"expires":1460718017,"correlator":"z9hG4bKPj3tCFJsqQlwwO8K2e7sBR7R7HEeEWH7mx","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"136a11be099122c7","nc":2,"expires":1460718017,"correlator":"z9hG4bKPjFJb.SSh9ecEE9vbbYuvbiUgrSuxxpanw","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"7c72fca765af6d50","nc":2,"expires":1460718017,"correlator":"z9hG4bKPjXkeIMtcitnU4yi3f21ntl8p9I8ZCOOXS","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"24c5643c1241b3ff","nc":2,"expires":1460718017,"correlator":"z9hG4bKPjlGgbTMAzVZLtQwJnhsfiybAQJwwGPpPV","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"784e2dfb0cd5c980","nc":2,"expires":1460718026,"correlator":"z9hG4bKPjv6HJ-d2ca-jYfJtPSvcA0z-Q0fcB7mMo","realm":"xflowresearch.com","qop":"auth","ha1":"915853456718dae6a86b6801965ee2d2"},{"type":"digest","nonce":"4f9ddb0137040fa15-04-2016 11:00:01.578 UTC Previous log was truncated by 15859 characters
```

#### Impact

Eventually you'll hit memory issues, if you store 24KB of data for too many subscribers.

#### Release and environment 

"Bulbasaur" release (probably any since nonce-count support went in?).

#### Steps to reproduce

Speculatively - set up a client that fails to register, but keeps trying?

### PR DESCRIPTION
**Pull request by sathiyan-sivathas**
When we fail to do an IMPI SET in memcached we have no hope of processing a challenge response so, send a 503 so we don't get into a REGISTER/401/REGISTER/401 loop.

Tested live and fixes #1404

### CODE REVIEW

File: src/authentication.cpp [hunk 1]
```diff
@@ -605,6 +605,16 @@ void create_challenge(pjsip_digest_credential* credentials,
       TRC_DEBUG("Sending %s to Chronos to set AV timer", chronos_body.c_str());
       chronos->send_post(timer_id, 30, "/authentication-timeout", chronos_body, get_trail(rdata));
     }
+    else
+    {
+      // We've failed to store the nonce in memcached, so we have no hope of
+      // successfuly authenticating any repsonse to a 401 Unauthorized.  Send
+      // a 503 Servce Unavailable instead.
```
Comment (rkd-msw) [inline src/authentication.cpp]: Typos: successfuly, Service

Comment (rkd-msw) [inline src/authentication.cpp]: We generally use 503 Service Unavailable to signify overload - can you use a different 5xx-class response, like Internal Server Error, here?

File: src/authentication.cpp [hunk 2]
```diff
@@ -605,6 +605,16 @@ void create_challenge(pjsip_digest_credential* credentials,
...
+      TRC_DEBUG("Failed to store nonce in memcached.");
```
Comment (rkd-msw) [inline src/authentication.cpp]: We normally wouldn't put full stops at the end of log messages.

File: src/authentication.cpp [hunk 3]
```diff
@@ -605,6 +605,16 @@ void create_challenge(pjsip_digest_credential* credentials,
...
+      tdata->msg->line.status.code = PJSIP_SC_SERVICE_UNAVAILABLE;
+      tdata->msg->line.status.reason = *pjsip_get_status_text(PJSIP_SC_SERVICE_UNAVAILABLE);
+      pjsip_tx_data_invalidate_msg(tdata);
```
Comment (rkd-msw) [inline src/authentication.cpp]: Given that we had to check the PJSIP code to see what this does, maybe worth a comment (here and below)?

**Comment by rkd-msw** [comment]
Looks good - one meaningful comment and a couple of typos/other tweaks.

**Comment by rkd-msw** [comment]
(Note that I'm about to freeze code to cut the release, so don't check this in for a bit)
