### PR TITLE
[Reviewer: Matt] Make ralf requests asynchronous

### LINKED ISSUE #1103: If all ralfs are dead, calls fail
When all ralfs are dead, calls fail with a 408. SAS traces are available.

### PR DESCRIPTION
**Pull request by eleanor-merry**
Matt, can you please review this change to make sending Ralf requests asynchronous. It's not complete (I've only tested live, there's no UTs), but I wanted to check this wasn't completely off. 

Fixes #1103

### CODE REVIEW

File: include/ralf_processor.h [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+  /// This function adds a ralf request to the pool. Actually sending
+  /// the Ralf request must be done in a separate thread to avoid
+  /// introducing unnecessary latencies in the call path.
+  /// @param rr         The RalfRequest to add to the queue
+  virtual void send_request_to_ralf(RalfRequest* rr);
+
+  static void exception_callback(RalfProcessor::RalfRequest* work)
+  {
+    // No recovery behaviour as this is asynchronos, so we can't sensibly
+    // respond
```
Comment (mirw) [inline include/ralf_processor.h]: Will we have logged, though?  In particular, should we SAS log?

File: include/ralf_processor.h [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+
+  /// This function adds a ralf request to the pool. Actually sending
+  /// the Ralf request must be done in a separate thread to avoid
+  /// introducing unnecessary latencies in the call path.
+  /// @param rr         The RalfRequest to add to the queue
+  virtual void send_request_to_ralf(RalfRequest* rr);
+
+  static void exception_callback(RalfProcessor::RalfRequest* work)
+  {
+    // No recovery behaviour as this is asynchronos, so we can't sensibly
```
Comment (bossmc) [inline include/ralf_processor.h]: sp. asynchronos

**Comment by mirw** [comment]
Generally, good looks code.  One question, though: how do we apply back pressure on this?  I'm nervous that the Ralf work could back up indefinitely.
